{
  "openapi": "3.1.1",
  "info": {
    "title": "fruits API",
    "description": "Public API to interact with your fruits portfolio.",
    "termsOfService": "https://fruits.co/terms",
    "contact": {
      "name": "fruits API Support",
      "url": "https://fruits.co/contact",
      "email": "dev@fruits.co"
    },
    "version": "0.0.5",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://api.fruits.co"
    }
  ],
  "tags": [
    {
      "name": "domains",
      "description": "Domain operations"
    },
    {
      "name": "webhooks",
      "description": "Webhook operations"
    },
    {
      "name": "events",
      "description": "Event operations"
    }
  ],
  "paths": {
    "/v1/domains": {
      "get": {
        "operationId": "DomainList",
        "summary": "List domains",
        "description": "List all domains in your portfolio, with optional filters and pagination.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.read"
            ]
          }
        ]
      }
    },
    "/v1/domains/bulk": {
      "patch": {
        "operationId": "DomainUpdateBulk",
        "summary": "Update domains",
        "description": "Update a list of domains through a filter.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "DomainDeleteBulk",
        "summary": "Delete domains",
        "description": "Delete a list of domains through a filter.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      }
    },
    "/v1/domains/{idOrName}": {
      "get": {
        "operationId": "DomainGet",
        "summary": "Get domain",
        "description": "Get the details of a domain.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.read"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "DomainDelete",
        "summary": "Delete domain",
        "description": "Delete a domain.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      }
    },
    "/v1/domains/{idOrName}/authcodes": {
      "post": {
        "operationId": "DomainAuthCodeCreate",
        "summary": "Create domain auth code",
        "description": "Create a new domain auth code for a domain.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      }
    },
    "/v1/imports": {
      "post": {
        "operationId": "DomainImportCreate",
        "summary": "Create domain import",
        "description": "Create a new domain import to add and/or update domains.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      }
    },
    "/v1/imports/{id}": {
      "get": {
        "operationId": "DomainImportGet",
        "summary": "Get domain import",
        "description": "Get the details of a domain import.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.read"
            ]
          }
        ]
      }
    },
    "/v1/negotiations": {
      "get": {
        "operationId": "NegotiationList",
        "summary": "List negotiations",
        "description": "List all negotiations in your account.",
        "tags": [
          "negotiations"
        ],
        "security": [
          {
            "oauth2": [
              "content.negotiation.read"
            ]
          }
        ]
      }
    },
    "/v1/negotiations/{id}": {
      "get": {
        "operationId": "NegotiationGet",
        "summary": "Get negotiation",
        "description": "Get the details of a negotiation.",
        "tags": [
          "negotiations"
        ],
        "security": [
          {
            "oauth2": [
              "content.negotiation.read"
            ]
          }
        ]
      }
    },
    "/v1/negotiations/{id}/messages": {
      "get": {
        "operationId": "NegotiationMessages",
        "summary": "List negotiation messages",
        "description": "List all messages of a negotiation.",
        "tags": [
          "negotiations"
        ],
        "security": [
          {
            "oauth2": [
              "content.negotiation.read"
            ]
          }
        ]
      }
    },
    "/v1/negotiations/{id}/messages/reply": {
      "post": {
        "operationId": "ReplyNegotiation",
        "summary": "Reply to a negotiation",
        "description": "Reply to a negotiation.",
        "tags": [
          "negotiations"
        ],
        "security": [
          {
            "oauth2": [
              "content.negotiation.write"
            ]
          }
        ]
      }
    },
    "/v1/negotiations/{id}/receipts/me": {
      "put": {
        "summary": "Set caller's last-read message pointer",
        "operationId": "NegotiationReadReceiptUpdate",
        "description": "Update the receipt of a negotiation.",
        "tags": [
          "negotiations"
        ],
        "security": [
          {
            "oauth2": [
              "content.negotiation.write"
            ]
          }
        ]
      }
    },
    "/v1/negotiations/{id}/cancel": {
      "post": {
        "operationId": "CancelNegotiation",
        "summary": "Cancel a negotiation",
        "description": "Cancel a negotiation.",
        "tags": [
          "negotiations"
        ],
        "security": [
          {
            "oauth2": [
              "content.negotiation.write"
            ]
          }
        ]
      }
    },
    "/v1/orders/sales": {
      "get": {
        "operationId": "SaleList",
        "summary": "List sales",
        "description": "List all sales in your account.",
        "tags": [
          "orders"
        ],
        "security": [
          {
            "oauth2": [
              "content.order.read"
            ]
          }
        ]
      }
    },
    "/v1/orders/sales/{idOrNumber}": {
      "get": {
        "operationId": "SaleGet",
        "summary": "Get sale",
        "description": "Get the details of a sale.",
        "tags": [
          "orders"
        ],
        "security": [
          {
            "oauth2": [
              "content.order.read"
            ]
          }
        ]
      }
    },
    "/v1/webhooks": {
      "get": {
        "operationId": "WebhookList",
        "summary": "List webhooks",
        "description": "List all webhooks in your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "WebhookCreate",
        "summary": "Create a webhook",
        "description": "Create a new webhook in your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.write"
            ]
          }
        ]
      }
    },
    "/v1/webhooks/{id}": {
      "put": {
        "operationId": "WebhookUpdate",
        "summary": "Update a webhook",
        "description": "Update an existing webhook in your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "WebhookDelete",
        "summary": "Delete a webhook",
        "description": "Delete an existing webhook from your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.write"
            ]
          }
        ]
      }
    }
  },
  "webhooks": {
    "event": {
      "post": {
        "summary": "Event",
        "operationId": "WebhookEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "sale.pending": {
      "post": {
        "summary": "Sale pending",
        "operationId": "WebhookSalePendingEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "sale.succeeded": {
      "post": {
        "summary": "Sale succeeded",
        "operationId": "WebhookSaleSucceededEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "sale.failed": {
      "post": {
        "summary": "Sale failed",
        "operationId": "WebhookSaleFailedEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "sale.cancelled": {
      "post": {
        "summary": "Sale cancelled",
        "operationId": "WebhookSaleCancelledEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "sale.requires_action": {
      "post": {
        "summary": "Sale requires action",
        "operationId": "WebhookSaleRequiresActionEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "sale.leased": {
      "post": {
        "summary": "Sale leased",
        "operationId": "WebhookSaleLeasedEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "negotiation.created": {
      "post": {
        "summary": "Negotiation created",
        "operationId": "WebhookNegotiationCreatedEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "negotiation.message.created": {
      "post": {
        "summary": "Negotiation message created",
        "operationId": "WebhookNegotiationMessageCreatedEvent",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "signature": {
        "type": "apiKey",
        "name": "X-Fruits-Signature",
        "in": "header"
      },
      "oauth2": {
        "type": "oauth2",
        "description": "OAuth2 authorization code and client credentials flow.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://api.fruits.co/oauth2/authorize",
            "tokenUrl": "https://api.fruits.co/oauth2/token",
            "scopes": {
              "content.domain.read": "Read access to domains",
              "content.domain.write": "Write access to domains",
              "account.admin.read": "Read access to account",
              "account.admin.write": "Write access to account",
              "content.order.read": "Read access to orders",
              "content.negotiation.read": "Read access to negotiations",
              "content.negotiation.write": "Write access to negotiations"
            }
          },
          "clientCredentials": {
            "tokenUrl": "https://api.fruits.co/oauth2/token",
            "scopes": {
              "platform.account.create": "Write access to accounts"
            }
          }
        }
      }
    }
  }
}