{
  "openapi": "3.1.1",
  "info": {
    "title": "fruits API",
    "description": "Public API to interact with your fruits portfolio.",
    "termsOfService": "https://fruits.co/terms",
    "contact": {
      "name": "fruits API Support",
      "url": "https://fruits.co/contact",
      "email": "dev@fruits.co"
    },
    "version": "0.0.3",
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://api.fruits.co"
    }
  ],
  "tags": [
    {
      "name": "domains",
      "description": "Domain operations"
    },
    {
      "name": "webhooks",
      "description": "Webhook operations"
    },
    {
      "name": "events",
      "description": "Event operations"
    }
  ],
  "paths": {
    "/v1/domains": {
      "get": {
        "operationId": "DomainList",
        "summary": "List domains",
        "description": "List all domains in your portfolio, with optional filters and pagination.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "DomainUpdateBulk",
        "summary": "Update domains",
        "description": "Update a list of domains through a filter.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      }
    },
    "/v1/domains/{idOrName}": {
      "get": {
        "operationId": "DomainGet",
        "summary": "Get domain",
        "description": "Get the details of a domain.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.read"
            ]
          }
        ]
      }
    },
    "/v1/domains/{idOrName}/authcodes": {
      "post": {
        "operationId": "DomainAuthCodeCreate",
        "summary": "Create domain auth code",
        "description": "Create a new domain auth code for a domain.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      }
    },
    "/v1/imports": {
      "post": {
        "operationId": "DomainImportCreate",
        "summary": "Create domain import",
        "description": "Create a new domain import to add and/or update domains.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.write"
            ]
          }
        ]
      }
    },
    "/v1/imports/{id}": {
      "get": {
        "operationId": "DomainImportGet",
        "summary": "Get domain import",
        "description": "Get the details of a domain import.",
        "tags": [
          "domains"
        ],
        "security": [
          {
            "oauth2": [
              "content.domain.read"
            ]
          }
        ]
      }
    },
    "/v1/webhooks": {
      "get": {
        "operationId": "WebhookList",
        "summary": "List webhooks",
        "description": "List all webhooks in your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "WebhookCreate",
        "summary": "Create a webhook",
        "description": "Create a new webhook in your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.write"
            ]
          }
        ]
      }
    },
    "/v1/webhooks/{id}": {
      "put": {
        "operationId": "WebhookUpdate",
        "summary": "Update a webhook",
        "description": "Update an existing webhook in your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "WebhookDelete",
        "summary": "Delete a webhook",
        "description": "Delete an existing webhook from your account.",
        "tags": [
          "webhooks"
        ],
        "security": [
          {
            "oauth2": [
              "account.admin.write"
            ]
          }
        ]
      }
    }
  },
  "webhooks": {
    "domainSalePending": {
      "post": {
        "summary": "Domain Sale Pending",
        "operationId": "DomainSalePending",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "domainSaleCancelled": {
      "post": {
        "summary": "Domain Sale Cancelled",
        "operationId": "DomainSaleCancelled",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "domainSaleSucceeded": {
      "post": {
        "summary": "Domain Sale Succeeded",
        "operationId": "DomainSaleSucceeded",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    },
    "domainSaleFailed": {
      "post": {
        "summary": "Domain Sale Failed",
        "operationId": "DomainSaleFailed",
        "tags": [
          "events"
        ],
        "security": [
          {
            "signature": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "signature": {
        "type": "apiKey",
        "name": "X-Fruits-Signature",
        "in": "header"
      },
      "oauth2": {
        "type": "oauth2",
        "description": "OAuth2 authorization code and client credentials flow.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://api.fruits.co/oauth2/authorize",
            "tokenUrl": "https://api.fruits.co/oauth2/token",
            "scopes": {
              "content:domain:read": "Read access to domains",
              "content:domain:write": "Write access to domains",
              "account:admin:read": "Read access to account",
              "account:admin:write": "Write access to account"
            }
          },
          "clientCredentials": {
            "tokenUrl": "https://api.fruits.co/oauth2/token",
            "scopes": {
              "platform:account:create": "Write access to accounts"
            }
          }
        }
      }
    }
  }
}